version: "3"

networks:
  tgl-api-graphql:
    external: true

services:
  app:
    container_name: tgl-api-nestjs-graphql
    build:
      context: .
      dockerfile: ./Dockerfile
    command: npm run start:dev
    image: tgl-api-nestjs-graphql
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - tgl-api-graphql
    depends_on:
      - database
    ports:
      - '${API_PORT}:${API_PORT}'
    environment:
      - MYSQL_HOST=database

  database:
    container_name: db-tgl-api
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME}
    ports:
      - '${MYSQL_PORT}:${MYSQL_PORT}'
    expose:
      - '${MYSQL_PORT}'
    networks:
      - tgl-api-graphql
    command: mysqld --innodb_use_native_aio=0 --default-authentication-plugin=mysql_native_password
    volumes:
      - /db/var/lib/mysql